// Generated by CoffeeScript 1.6.3
var NSQDConnection, WriterNSQDConnection, _ref;

_ref = require('./nsqdconnection'), NSQDConnection = _ref.NSQDConnection, WriterNSQDConnection = _ref.WriterNSQDConnection;

module.exports = {
  Reader: require('./reader'),
  Writer: require('./writer'),
  NSQDConnection: NSQDConnection,
  WriterNSQDConnection: WriterNSQDConnection
};
